# Kizazi Kijacho Raw Data Extraction and Data Analysis

In [1]:
import csv
import json
from collections import defaultdict
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column
from sqlalchemy.sql import select
import os
import getpass
from datetime import datetime
import logging
from io import StringIO
from sqlalchemy import String

In [2]:
# Create a database engine and connect to the database
# engine = sqlalchemy.create_engine('postgresql://data_warehouse:strong_pass@localhost:5434/database_name')
# For localhost you would need to do port forwarding

logging.basicConfig()
logging.getLogger("sqlalchemy.engine").setLevel(logging.INFO)

log_stream = StringIO()
handler = logging.StreamHandler(log_stream)
logging.getLogger("sqlalchemy.engine").addHandler(handler)

engine = create_engine('postgresql+psycopg2://date_warehouse:strongpass@localhost:5434/database_name', echo=True)

In [3]:
# Connect to the database
connection = engine.connect()

2024-05-15 09:23:29,682 INFO sqlalchemy.engine.Engine select pg_catalog.version()

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()

2024-05-15 09:23:29,686 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2024-05-15 09:23:30,901 INFO sqlalchemy.engine.Engine select current_schema()

INFO:sqlalchemy.engine.Engine:select current_schema()

2024-05-15 09:23:30,905 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2024-05-15 09:23:32,136 INFO sqlalchemy.engine.Engine show standard_conforming_strings

INFO:sqlalchemy.engine.Engine:show standard_conforming_strings

2024-05-15 09:23:32,141 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

In [4]:
# Fetch All Events data
raw_event_metadata = MetaData()
raw_event_table = Table('raw_events', raw_event_metadata, schema='opensrp')
raw_event_select_stmnt = select('*').select_from(raw_event_table)
raw_events_results = connection.execute(raw_event_select_stmnt).fetchall()

2024-05-15 09:23:41,527 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-15 09:23:41,529 INFO sqlalchemy.engine.Engine SELECT *
FROM opensrp.raw_events

INFO:sqlalchemy.engine.Engine:SELECT *
FROM opensrp.raw_events

2024-05-15 09:23:41,531 INFO sqlalchemy.engine.Engine [generated in 0.00459s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00459s] {}

In [5]:
# This is an array list of raw events
# Add raw json event data to a list for processing
list_of_raw_json = []
for raw_json in raw_events_results:
    list_of_raw_json.append(raw_json[1])
print(len(list_of_raw_json))

58530

In [6]:
# Location data
location_metadata = MetaData()
location_table = Table('kk_locations', location_metadata, schema='opensrp_ext')

# Select Location Data Statement
location_select_stmnt = select('*').select_from(location_table)
# Execute sql statements to get locations
location_results = connection.execute(location_select_stmnt)
# Create location dataframe
location_df = pd.DataFrame(location_results.all(), columns=location_results.keys())

2024-05-15 09:41:58,090 INFO sqlalchemy.engine.Engine SELECT *
FROM opensrp_ext.kk_locations

INFO:sqlalchemy.engine.Engine:SELECT *
FROM opensrp_ext.kk_locations

2024-05-15 09:41:58,092 INFO sqlalchemy.engine.Engine [generated in 0.00205s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00205s] {}

In [7]:
location_df.head()

,id,village,hf,ward,district,region
0,35184a8e-53aa-4729-8b94-05c27bdb0941,Idaho,Mafene Dispensary,Lumuma,Mpwapwa,Dodoma
1,6eb3708c-0d6b-42b7-b066-b21b86152f41,Masene,Mafene Dispensary,Lumuma,Mpwapwa,Dodoma
2,ab3180c3-ad77-4de4-94b3-87dad88b13d7,Makose,Makose Dispensary,Massa,Mpwapwa,Dodoma
3,a962a054-c49a-4e4e-8da8-fc83dc1995c8,Mkoleko,Makose Dispensary,Massa,Mpwapwa,Dodoma
4,209e2a59-2704-4522-89ca-c66fe141414f,Matonya,Matonya Dispensary,Galigali,Mpwapwa,Dodoma

In [8]:
# Read clients ids for matching of house holds
clients_details_metadata = MetaData()
clients_details_table = Table('client_details_with_edi_ids_new', clients_details_metadata, schema='opensrp_ext')

# Create a statement to read from the view and create a dataframe
client_details_select_stmnt = select('*').select_from(clients_details_table)

#Execute select statement
client_details_select_results = connection.execute(client_details_select_stmnt)

client_details_dataframe = pd.DataFrame(client_details_select_results.all(), 
                                        columns=client_details_select_results.keys())

client_details_dataframe.head()

2024-05-15 09:42:20,522 INFO sqlalchemy.engine.Engine SELECT *
FROM opensrp_ext.client_details_with_edi_ids_new

INFO:sqlalchemy.engine.Engine:SELECT *
FROM opensrp_ext.client_details_with_edi_ids_new

2024-05-15 09:42:20,525 INFO sqlalchemy.engine.Engine [generated in 0.00317s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00317s] {}

,base_entity_id,family_id,household_head_id,head_first_name,head_last_name,primary_caregiver_id,primary_caregiver_first_name,primary_caregiver_last_name,edi_id,family_name
0,0006d75a-06c6-47b2-8a4e-2b69e370599f,ce3342f6-8351-45c6-a522-3d689dcd128b,0006d75a-06c6-47b2-8a4e-2b69e370599f,Mariam Mazengo,0,0006d75a-06c6-47b2-8a4e-2b69e370599f,Mariam Mazengo,0,03302,Masukuzi
1,000eeaaa-b074-43da-a840-388bd0621eff,931a9f3b-e81a-47fc-8bad-824fe693e161,12004a9e-75b6-41aa-b6dc-8eb09a4573e6,Helena,0,12004a9e-75b6-41aa-b6dc-8eb09a4573e6,Helena,0,None,Kusenha
2,000f9512-c557-46d5-9c3a-d2cea5af827e,468d181f-5e1d-417c-a876-b32efadbf08e,e8a6a2dd-580b-4fa8-8ec3-87216e732875,Furaha Razaro,Kusenha,e8a6a2dd-580b-4fa8-8ec3-87216e732875,Furaha Razaro,Kusenha,None,Mwaluko
3,001708ce-6556-4ecc-962f-d6d4d78c4ea7,001708ce-6556-4ecc-962f-d6d4d78c4ea7,9ceb50df-4632-4857-8297-9f3580684140,None,None,9ceb50df-4632-4857-8297-9f3580684140,None,None,None,Mrisho
4,001a5960-916a-4cb6-a4bf-a11b7bfeb940,caea356e-2f5e-47e3-9807-8a5306d91e14,eed45d74-9a04-4787-9f9d-043eafbee955,Agnes Enock,Pauloo,eed45d74-9a04-4787-9f9d-043eafbee955,Agnes Enock,Pauloo,None,Simon

In [9]:
fields_to_filter_out = [
    'surname', 
    'fam_name', 
    'name_person_assist', 
    'phone_number', 
    'phone_person_assist', 
    'surname_child_1', 
    'father_number_child_1', 
    'surname_child_2', 
    'father_number_child_2', 
    'surname_child_3', 
    'father_number_child_3', 
    'surname_child_4', 
    'father_number_child_4', 
    'surname_child_5', 
    'father_number_child_5', 
    'surname_child_6', 
    'father_number_child_6', 
    'surname_child_7', 
    'father_number_child_7', 
    'same_as_fam_name', 
    'same_as_fam_name_child_1', 
    'same_as_fam_name_child_2', 
    'same_as_fam_name_child_3', 
    'same_as_fam_name_child_4', 
    'same_as_fam_name_child_5', 
    'same_as_fam_name_child_6', 
    'same_as_fam_name_child_7'
    'first_name_child_1', 
    'first_name_child_2', 
    'first_name_child_3', 
    'first_name_child_4', 
    'first_name_child_5', 
    'first_name_child_6', 
    'first_name_child_7', 
    'lastName', 
    'last_name', 
    'first_name', 
    'middle_name', 
    'middle_name_child_1', 
    'middle_name_child_2', 
    'middle_name_child_3', 
    'middle_name_child_4', 
    'middle_name_child_5', 
    'middle_name_child_6', 
    'middle_name_child_7', 
    'caregiver_surname', 
    'caregiver_first_name', 
    'other_phone_number', 
    'father_number'
]

In [10]:
def get_child_unique_id(full_json):
    for obs in full_json['obs']:
        if obs['formSubmissionField'] == 'repeatvalueslist':
            child_repeat_dict = json.loads(obs['values'][0])
            child_ids = []
            for child_info in child_repeat_dict:
                child_ids.append(child_info['unique_id'])
            return child_ids
    
def get_human_readable_value(obs_dict):
    concat_value = ''
    for item_index in range(len(obs_dict)):
        try:
            if isinstance(obs_dict[item_index], list):
                try:
                    if item_index == 0:
                        concat_value += obs_dict[item_index][0]
                    else:
                    
                        concat_value += ', ' + obs_dict[item_index][0]
                except IndexError:
                    concat_value += ', ' + 'None'
            else:
                if item_index == 0:
                    concat_value += obs_dict[item_index]
                else:
                    concat_value += ', ' + obs_dict[item_index]
        except TypeError:
            concat_value = "None"
    return concat_value
# This list is for visit events
new_list_of_jsons = []
# This list is for group sessions events
new_list_of_jsons_gs = []
location_id = ''
obs_list = {}
for i in range(len(list_of_raw_json)):
    only_one_json = list_of_raw_json[i]
    try:
        form_id = only_one_json.get('_id')
        base_entity_id = only_one_json.get('baseEntityId')
        event_type = only_one_json.get('eventType')
        provider_id = only_one_json.get('providerId')
        location_id = only_one_json.get('locationId')
        event_date = only_one_json.get('eventDate')
        date_created = only_one_json.get('dateCreated')
        team = only_one_json.get('team')
        child_unique_id = []
        if event_type == 'Pregnancy Outcome':
            child_unique_id = get_child_unique_id(only_one_json)
        obs_list = {}
        for obs in only_one_json['obs']:
            field_name = ''
            data_point_value = ''
            if obs['formSubmissionField']:
                field_name = obs['formSubmissionField']
                if child_unique_id is not None:
                    if len(child_unique_id) > 0:
                        for j in range(len(child_unique_id)):
                            if child_unique_id[j] in field_name:
                                field_name = field_name.replace('_' + child_unique_id[j], f'_child_{j+1}')
            # Filter out identifying information
            if field_name not in fields_to_filter_out:
                if obs['humanReadableValues']:
                    data_point_value = get_human_readable_value(obs['humanReadableValues'])
                else:
                    if obs['values']:
                        data_point_value = get_human_readable_value(obs['values'])
                if len(obs_list) > 0:
                    if any(field_name not in d for d in obs_list):
                        obs_list[field_name] = data_point_value
                else:
                    obs_list[field_name] = data_point_value
        
    except KeyError as ke:
        print('Key not there: ', ke)
    if event_type == 'Group Session' or event_type == 'Child Group Session' or event_type == 'Group Session Not Done':
        the_temp_json = {'id': form_id, 
                     'location_id': location_id, 
                     'base_entity_id': base_entity_id, 
                     'event_type': event_type, 
                     'provider_id': provider_id,
                     'event_date': event_date,
                     'date_created': date_created,
                     'team': team,
                     'obs': obs_list
                    }
        print("This one is a group session event")
        new_list_of_jsons_gs.append(the_temp_json)
    else:
        the_temp_json = {'id': form_id, 
                     'location_id': location_id, 
                     'base_entity_id': base_entity_id, 
                     'event_type': event_type, 
                     'provider_id': provider_id,
                     'event_date': event_date,
                     'date_created': date_created,
                     'team': team,
                     'obs': obs_list
                    }
        new_list_of_jsons.append(the_temp_json)

wh_df = pd.json_normalize(new_list_of_jsons)
group_session_events_df = pd.json_normalize(new_list_of_jsons_gs)
#obs_df = pd.json_normalize(["id","danger_signs_present", "end", "save_n_refer"], wh_df['obs'])
#whole_thing_df = pd.concat([wh_df[["form_id", "base_entity_id"]].reset_index(), obs_df], axis=1)

Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
This one is a group session event
This one is a group session event
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'
Key not there:  'humanReadableValues'

In [11]:
group_session_events_df.head()

,id,location_id,base_entity_id,event_type,provider_id,event_date,date_created,team,obs.session_id,obs.session_date,...,obs.session_not_done_reason,obs.gps,obs.gps_latitude,obs.gps_longitude,obs.gps_altitude,obs.gps_accuracy,obs.other_people_present_other,obs.care_giver_representatives,obs.care_giver_representatives_other,obs.session_not_done_reason_other
0,0f2ae316-2852-4e3e-bb95-a4d34be5a56a,a40c48ad-8545-42fa-aa23-f5a5e216619f,06764ae3-c75b-4ec1-a996-5fcd3f3966ed,Child Group Session,kk053,2024-01-24T19:32:35.731+03:00,2024-01-28T07:55:40.252+03:00,team035,40b3b465-94ff-4f7e-bf62-5aa7b2923758,2024-01-24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,f9d6ac88-031c-4c9b-9fd3-bb6acdca95ee,c864174b-7592-4af7-bfd9-6a3304f93b3c,11e7ed5a-d9bb-4f34-8535-e71bf07ba0cf,Child Group Session,kk016,2024-01-22T19:36:03.102+03:00,2024-01-31T13:45:07.150+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6a46398b-58f1-4473-bcf9-9d6d473f26cd,c864174b-7592-4af7-bfd9-6a3304f93b3c,883ef441-e58b-49a8-8852-2a1e38839ea4,Child Group Session,kk016,2024-01-22T19:36:03.200+03:00,2024-01-31T13:45:07.158+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4ff23e8a-a9d3-40fa-94cd-4584438ee737,c864174b-7592-4af7-bfd9-6a3304f93b3c,fc5b98f0-2fad-483c-a5e2-9fed8f443149,Child Group Session,kk016,2024-01-22T19:36:03.302+03:00,2024-01-31T13:45:07.166+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4669aeca-399e-4475-b77c-e7a022a9c397,c864174b-7592-4af7-bfd9-6a3304f93b3c,854906cd-4037-4daa-9256-97031eae4fc2,Child Group Session,kk016,2024-01-22T19:36:03.404+03:00,2024-01-31T13:45:07.174+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Join the data with the location information
joined_df = wh_df.merge(location_df, how='left', left_on='location_id', right_on='id')
gs_joined_location = group_session_events_df.merge(location_df, how='left', left_on='location_id', right_on='id')

In [13]:
# Remove duplicate location id id_y
joined_df.drop('id_y', axis=1, inplace=True)

joined_df.rename(columns={'id_x': 'id'}, inplace=True)

joined_df.head()

,id,location_id,base_entity_id,event_type,provider_id,event_date,date_created,team,obs.last_menstrual_period,obs.gest_age_note,...,obs.miscarriage_date_unknown,obs.miscarriage_days,obs.already_taking_art,obs.received_surua_rubella2,obs.received_vitamin_a_droplets,village,hf,ward,district,region
0,fe12d13d-998f-421c-a0b2-d587dad49e45,1980d4cd-1966-4c17-b8bc-a134d3199b26,fa3f4a41-4f16-4fc3-998b-eedf8c5e1613,Family Member Registration,kk145,2023-01-05T03:00:00.000+03:00,2023-01-05T18:42:19.837+03:00,team085,20-05-2022,32 Wiki,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a23f8845-a401-458d-a4e2-91789cad56b7,d9e02af7-6983-4a13-b683-9baf6396c6b1,6a49808e-a9a7-4719-8ff2-94bd5155f009,ANC Home Visit,kk083,2023-01-03T03:00:00.000+03:00,2023-01-05T19:29:21.536+03:00,team053,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Kitelela,Kitelela Dispensary,Nzuguni,Dodoma City,Dodoma
2,ff42842b-d46b-439d-83bc-84cdce01b34b,9f0b9674-68b6-494c-9315-7d48b4e9f9c9,0763cc8f-26b4-4bb5-a3be-1da0061906b7,Family Member Registration,kk006,2022-10-27T03:00:00.000+03:00,2022-10-28T14:49:01.120+03:00,team004,20-03-2022,31 Wiki,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1837d71c-4120-4198-b15d-31d91e9d5671,9f0b9674-68b6-494c-9315-7d48b4e9f9c9,0763cc8f-26b4-4bb5-a3be-1da0061906b7,ANC Registration,kk006,2022-10-27T03:00:00.000+03:00,2022-10-28T14:49:01.133+03:00,team004,20-03-2022,31 Wiki,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d8b8f9eb-44b8-43a8-8c38-e15d43912a7f,9f0b9674-68b6-494c-9315-7d48b4e9f9c9,bf32a6d1-b86a-4540-93a4-8b36c5b28aec,Family Member Registration,kk006,2022-10-27T03:00:00.000+03:00,2022-10-28T14:49:01.145+03:00,team004,22-04-2022,26 Wiki,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Remove duplicate location_id id_y for the group sessions
gs_joined_location.drop('id_y', axis=1, inplace=True)
gs_joined_location.rename(columns={'id_x': 'id'}, inplace=True)
gs_joined_location.head()

,id,location_id,base_entity_id,event_type,provider_id,event_date,date_created,team,obs.session_id,obs.session_date,...,obs.gps_accuracy,obs.other_people_present_other,obs.care_giver_representatives,obs.care_giver_representatives_other,obs.session_not_done_reason_other,village,hf,ward,district,region
0,0f2ae316-2852-4e3e-bb95-a4d34be5a56a,a40c48ad-8545-42fa-aa23-f5a5e216619f,06764ae3-c75b-4ec1-a996-5fcd3f3966ed,Child Group Session,kk053,2024-01-24T19:32:35.731+03:00,2024-01-28T07:55:40.252+03:00,team035,40b3b465-94ff-4f7e-bf62-5aa7b2923758,2024-01-24,...,NaN,NaN,NaN,NaN,NaN,Ibihwa,Ibihwa Dispensary,Ibihwa,Bahi,Dodoma
1,f9d6ac88-031c-4c9b-9fd3-bb6acdca95ee,c864174b-7592-4af7-bfd9-6a3304f93b3c,11e7ed5a-d9bb-4f34-8535-e71bf07ba0cf,Child Group Session,kk016,2024-01-22T19:36:03.102+03:00,2024-01-31T13:45:07.150+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma
2,6a46398b-58f1-4473-bcf9-9d6d473f26cd,c864174b-7592-4af7-bfd9-6a3304f93b3c,883ef441-e58b-49a8-8852-2a1e38839ea4,Child Group Session,kk016,2024-01-22T19:36:03.200+03:00,2024-01-31T13:45:07.158+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma
3,4ff23e8a-a9d3-40fa-94cd-4584438ee737,c864174b-7592-4af7-bfd9-6a3304f93b3c,fc5b98f0-2fad-483c-a5e2-9fed8f443149,Child Group Session,kk016,2024-01-22T19:36:03.302+03:00,2024-01-31T13:45:07.166+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma
4,4669aeca-399e-4475-b77c-e7a022a9c397,c864174b-7592-4af7-bfd9-6a3304f93b3c,854906cd-4037-4daa-9256-97031eae4fc2,Child Group Session,kk016,2024-01-22T19:36:03.404+03:00,2024-01-31T13:45:07.174+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,NaN,NaN,NaN,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma

In [15]:
# This merges the 
events_df_with_client_details = joined_df.merge(client_details_dataframe, how='left', left_on='base_entity_id', right_on='base_entity_id')
gs_with_client_details = gs_joined_location.merge(client_details_dataframe, how='left', left_on='base_entity_id', right_on='base_entity_id')

In [16]:

# CHW Data (Name of the chw)
chw_meta_data = MetaData()

chw_details = Table('chw_full_list', chw_meta_data,
                    Column('provider_id', String),
                    Column('chw', String),
                    schema='opensrp_ext'
                   )

# Select provider id and chw fullname
chw_details_select_stmnt = select(chw_details.c.provider_id, chw_details.c.chw)

#Execute the chw details select statement
chw_details_results = connection.execute(chw_details_select_stmnt)

chw_details_df = pd.DataFrame(chw_details_results.all(), columns=chw_details_results.keys())

2024-05-15 09:43:32,236 INFO sqlalchemy.engine.Engine SELECT opensrp_ext.chw_full_list.provider_id, opensrp_ext.chw_full_list.chw
FROM opensrp_ext.chw_full_list

INFO:sqlalchemy.engine.Engine:SELECT opensrp_ext.chw_full_list.provider_id, opensrp_ext.chw_full_list.chw
FROM opensrp_ext.chw_full_list

2024-05-15 09:43:32,238 INFO sqlalchemy.engine.Engine [generated in 0.00229s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00229s] {}

In [17]:
events_df_with_client_details_and_chw_details = events_df_with_client_details.merge(
    chw_details_df, 
    how='left', 
    left_on='provider_id', 
    right_on='provider_id'
)

In [18]:
def get_file_path(type_of_raw_data):
    documents_folder_path = os.path.expanduser('~/Documents')
    data_work_folder = 'DataWork'
    project_name = 'KizaziKijacho'
    report_month = datetime.now().strftime('%B')
    report_date = datetime.now().strftime('%Y%m%d')
    file_name = f'{report_date}{project_name}{type_of_raw_data}.csv'
    folder_path = os.path.join(documents_folder_path, data_work_folder, project_name, report_month)
    
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    file_path = os.path.join(folder_path, file_name)
    return file_path

In [19]:
# This needs to be refactored to include the function to create a directory and file path
# Save visit data in a csv file

documents_folder_path = os.path.expanduser('~/Documents')
data_work_folder = 'DataWork'
project_name = 'KizaziKijacho'
report_month = datetime.now().strftime('%B')
report_date = datetime.now().strftime('%Y%m%d')
file_name = f'{report_date}{project_name}RawData.csv'
folder_path = os.path.join(documents_folder_path, data_work_folder, project_name, report_month)

if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    
file_path = os.path.join(folder_path, file_name)
print(f'Saving the raw data in CSV to {file_path}...')

events_df_with_client_details_and_chw_details.to_csv(file_path)

print(f'CSV file {file_path} has been created successfully.')

Saving the raw data in CSV to /home/gosso/Documents/DataWork/KizaziKijacho/May/20240515KizaziKijachoRawData.csv...
CSV file /home/gosso/Documents/DataWork/KizaziKijacho/May/20240515KizaziKijachoRawData.csv has been created successfully.

In [20]:
# Drop personal identifying information
gs_with_client_details.drop('head_first_name', axis=1, inplace=True)
gs_with_client_details.drop('head_last_name', axis=1, inplace=True)
gs_with_client_details.drop('primary_caregiver_first_name', axis=1, inplace=True)
gs_with_client_details.drop('primary_caregiver_last_name', axis=1, inplace=True)
gs_with_client_details.drop('family_name', axis=1, inplace=True)
gs_with_client_details.head()

,id,location_id,base_entity_id,event_type,provider_id,event_date,date_created,team,obs.session_id,obs.session_date,...,obs.session_not_done_reason_other,village,hf,ward,district,region,family_id,household_head_id,primary_caregiver_id,edi_id
0,0f2ae316-2852-4e3e-bb95-a4d34be5a56a,a40c48ad-8545-42fa-aa23-f5a5e216619f,06764ae3-c75b-4ec1-a996-5fcd3f3966ed,Child Group Session,kk053,2024-01-24T19:32:35.731+03:00,2024-01-28T07:55:40.252+03:00,team035,40b3b465-94ff-4f7e-bf62-5aa7b2923758,2024-01-24,...,NaN,Ibihwa,Ibihwa Dispensary,Ibihwa,Bahi,Dodoma,41b218aa-0a9d-485a-ad04-861d185b96f7,141c6784-51a2-4889-9a81-f8ff3b59cba7,141c6784-51a2-4889-9a81-f8ff3b59cba7,None
1,f9d6ac88-031c-4c9b-9fd3-bb6acdca95ee,c864174b-7592-4af7-bfd9-6a3304f93b3c,11e7ed5a-d9bb-4f34-8535-e71bf07ba0cf,Child Group Session,kk016,2024-01-22T19:36:03.102+03:00,2024-01-31T13:45:07.150+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma,435a0e3e-6201-4e38-b196-544f9a6139d4,6189a0e4-d516-4bab-b66a-e2e3581bae5a,6189a0e4-d516-4bab-b66a-e2e3581bae5a,12006
2,6a46398b-58f1-4473-bcf9-9d6d473f26cd,c864174b-7592-4af7-bfd9-6a3304f93b3c,883ef441-e58b-49a8-8852-2a1e38839ea4,Child Group Session,kk016,2024-01-22T19:36:03.200+03:00,2024-01-31T13:45:07.158+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma,f13d262c-0e13-48ad-bdeb-a3513b4abc8c,31b7d858-b90f-467a-be02-0f5c74a3687d,31b7d858-b90f-467a-be02-0f5c74a3687d,12005
3,4ff23e8a-a9d3-40fa-94cd-4584438ee737,c864174b-7592-4af7-bfd9-6a3304f93b3c,fc5b98f0-2fad-483c-a5e2-9fed8f443149,Child Group Session,kk016,2024-01-22T19:36:03.302+03:00,2024-01-31T13:45:07.166+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma,aded62b6-9f91-412b-8ba6-2431e16a7893,c5b437ae-4ccb-4532-bc7f-a61e9d05ec15,c5b437ae-4ccb-4532-bc7f-a61e9d05ec15,12008
4,4669aeca-399e-4475-b77c-e7a022a9c397,c864174b-7592-4af7-bfd9-6a3304f93b3c,854906cd-4037-4daa-9256-97031eae4fc2,Child Group Session,kk016,2024-01-22T19:36:03.404+03:00,2024-01-31T13:45:07.174+03:00,team010,7d2f75ec-c84e-415b-8b1c-32423d2234d1,2024-01-22,...,NaN,Njiapanda,Chogola Dispensary,Massa,Mpwapwa,Dodoma,03d96462-0584-4bd4-a677-97260c4cd533,d6e61827-e878-4e5c-8b63-c19d74550304,d6e61827-e878-4e5c-8b63-c19d74550304,12007

In [21]:
gs_raw_data_file_path = get_file_path('GSRawData')
print(f'Saving the raw data in CSV to {gs_raw_data_file_path}...')
# Save group sessions data in a csv
gs_with_client_details.to_csv(gs_raw_data_file_path)
print(f'CSV file {file_path} has been created successfully.')

Saving the raw data in CSV to /home/gosso/Documents/DataWork/KizaziKijacho/May/20240515KizaziKijachoGSRawData.csv...
CSV file /home/gosso/Documents/DataWork/KizaziKijacho/May/20240515KizaziKijachoRawData.csv has been created successfully.

## Data Analysis and Queries

In [ ]:
def open_csv_file_in_df(file_name):
    documents_folder_path = os.path.expanduser('~/Documents/DataWork/RawCSVs')
    file_path = os.path.join(documents_folder_path, file_name)
    pd_file = pd.read_csv(file_path)
    return pd_file

In [ ]:
raw_event_to_play = open_csv_file_in_df('20240227KizaziKijachoRawData.csv')

### Mother Entity ID Different from the PrimaryCaregiver

In [ ]:
mother_diff_from_pc = open_csv_file_in_df('MotherDifferPC.csv')
mother_diff_from_pc.head

In [ ]:
raw_event_to_play = events_df_with_client_details_and_chw_details

In [ ]:
mother_diff_from_pc['family_id'].unique()[4]

In [ ]:
raw_event_to_play[
    raw_event_to_play['family_id'].isin([mother_diff_from_pc['family_id'].unique()[4]])][
        [
        'base_entity_id',
        'event_type',
        'event_date', 
        'family_id', 
        'household_head_id', 
        'primary_caregiver_id'
        ]
                                                                                        ]

### Head of HouseHold different from PrimaryCaregiver

In [ ]:
HeadNoInfo = open_csv_file_in_df('HeadNoInfo.csv')
HeadNoInfo.head

In [ ]:
filtered_value = raw_event_to_play[
    raw_event_to_play['family_id'].isin([HeadNoInfo['family_id'].unique()[1]])]

In [ ]:
filtered_value.query('event_type == "Family Member Registration"').dropna(axis=1)

### Child Visit Number None

In [ ]:
visit_number_none_data = open_csv_file_in_df('Visit_number_non.csv')
visit_number_none_data_filtered_value = raw_event_to_play[
    raw_event_to_play['base_entity_id'].isin(visit_number_none_data['base_entity_id'])
]

In [ ]:
visit_number_none_data_filtered_value[(visit_number_none_data_filtered_value['obs.visit_number'] == 'None')]

In [ ]:
len(raw_event_to_play[(raw_event_to_play['event_type'] == 'Family Member Registration') | (raw_event_to_play['event_type'] == 'PNC Child Registration')]['base_entity_id'].unique())

## Missing Data

In [21]:
raw_event_to_play.query('event_type == "Pregnancy Outcome"').dropna(axis=1).query(('`obs.preg_outcome` == "Matokeo ya ujauzito *"'))[['obs.start', 'base_entity_id']]

                 obs.start                        base_entity_id
343    2023-01-01 13:19:23  28f7ac9d-9090-4d91-ab04-ced431068aca
499    2022-11-23 17:59:21  79766af5-2083-434a-85d4-d0023af86e85
1109   2022-12-04 15:57:51  aad06ae1-9631-4dce-bbbd-f9eaee5be1f4
1199   2022-12-07 21:14:47  401ab03c-612f-43fd-97f2-e44bba0ea923
1434   2022-11-23 18:00:00  79766af5-2083-434a-85d4-d0023af86e85
...                    ...                                   ...
25447  2023-04-19 08:58:53  58b83277-615a-48a2-997e-127af8b2cda4
42212  2022-11-30 13:19:14  8ed864bc-3a45-4797-b3a5-4a0da2a1ef77
42266  2022-12-07 10:57:45  401ab03c-612f-43fd-97f2-e44bba0ea923
42687  2022-12-17 17:30:12  a3bf14e6-e31e-400a-9c9d-3962cbf64149
43763  2022-12-19 10:01:56  af1437ab-4f98-4b86-8454-a685cc92791b

[146 rows x 2 columns]